
CREATE USER ${DB_USER} WITH PASSWORD ${DB_PASSWORD};

CREATE DATABASE ${DB_NAME} WITH OWNER ${DB_USER};

ALTER DATABASE ${DB_NAME} SET timezone TO "Asia/Singapore";

GRANT ALL PRIVILEGES ON DATABASE ${DB_NAME} to ${DB_USER};



