version: "3.8"
services:
  db:
    container_name: pg_container_imda
    image: postgres:14.6
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      TZ: GMT+8
    ports:
      - "6433:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./src/resources/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - postgres
volumes:
  postgres:
networks:
  postgres:
